#!/usr/bin/env bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P  )"
export PATH="${PATH}:$HOME/.config/leftwm/themes/default/bin"

xrdb ~/.Xresources
getcolors() {
    FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
    BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
    BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
    RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
    GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
    YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
    BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
}

if [ -f "/tmp/leftwm-theme-down"  ]; then
        /tmp/leftwm-theme-down
        rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

killall -9 xsettingsd dunst picom

dunst \
-geom "280x50-10+42" -frame_width "1" -font "Iosevka Custom 9" \
-lb "#282A36" -lf "#F8F8F2" -lfr "#BD93F9" \
-nb "#282A36" -nf "#F8F8F2" -nfr "#BD93F9" \
-cb "#282A36" -cf "#FF5555" -cfr "#FF5555" &

xsettingsd &
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

xsetroot -cursor_name left_ptr &
picom --config ~/.config/leftwm/themes/default/picom.conf &
batify -c 10 -i 30 -l 20 &

echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe &

nitrogen --restore &
exec mpd &

bspcolors &
bspbar &
