#!/bin/sh

export PATH="${PATH}:$HOME/.config/awesome/bin"

xrdb ~/.Xresources
getcolors() {
    FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
    BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
    BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
    RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
    GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
    YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
    BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
}
getcolors

killall -9 xsettingsd dunst picom batify polybar conky

dunst -geom "280x50-10+34" -max_icon_size 16 -frame_width "1" -font "Iosevka Custom 9" -lb $BACKGROUND -lf $FOREGROUND -lfr $BLUE -nb $BACKGROUND -nf $FOREGROUND -nfr $BLUE -cb $BACKGROUND -cf $RED -cfr $RED &

xsettingsd &
if [[ ! `pidof xfce-polkit`  ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

xsetroot -cursor_name left_ptr &
picom &
batify -i 30 -l 20 -c 10 &
emacs --daemon &

nitrogen --restore &
exec mpd &
#conky -c /home/tempp/.conky/Titus.conkyrc &

bspcolors &
